### ISSUE TITLE
Icon Assets

### ISSUE THREAD

**Issue by skaldarnar** [Terasology/PlantPack#5]
I thought about this for some days now, and finally I want to come up with a discussion how to handle this topic.

Currently, only assets that are very general for plants are stored in this module (i.e. only icons for fruits are in here, but not for flour, ...). Any further processed items are defined by other modules, e.g. WaS defines cookedCorn and so on. 
As much as I like this separation of the actual items as objects, thinking from the art point of view a lot of the used icons can be re-used by other modules. 

Therefore, I would like to have sets/groups of icons in this module:
- Corn, corn flour
- wheat, straw, white flour
- ...

Please let me hear what you think about this, @MarcinSc, @esapetri, @Cervator.

**Comment by skaldarnar** [comment]
https://forum.terasology.org/threads/best-practice-module-scope-and-content.998/

**Comment by jdrueckert** [comment]
There's only a limited number of icons in this module right now and I don't expect a lot to be added any time soon, especially with https://github.com/Terasology/AdditionalFruits and https://github.com/Terasology/AdditionalVegetables around.
The module scope discussion definitely is still relevant, but I think that it should not be tracked in an issue in this specific module and that it will come up intuitively in the context of the module overhaul anyway.
