### ISSUE TITLE
Rename items.png to fruits.png

### ISSUE THREAD

**Issue by skaldarnar** [Terasology/PlantPack#6]
This one depends a bit on the further usage of PlantPack and whether Farming will be seperated. If we keep just one icon atlas `items` is fine, but with several icon atlas files it would make sense to have proper labels.

**Comment by jdrueckert** [comment]
`items` atlas still has only 10 icons in it (mostly vegetables).
I don't think this will change anytime soon and if it does, I guess we'll come back to splitting up and renaming things intuitively.
